# Generated by Django 4.2.8 on 2023-12-18 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import streaming.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=streaming.models.videoPath)),
                ('croppedTime', models.DateTimeField(verbose_name='Date and time when video updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
