# Generated by Django 4.2.8 on 2023-12-19 05:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='fileID',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
