# Generated by Django 4.2.8 on 2023-12-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_stream_fileid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='fileID',
            new_name='streamID',
        ),
    ]
