# Generated by Django 4.2.8 on 2023-12-17 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="Date and time when user's belongings are lost")),
                ('thumbnail', models.ImageField(upload_to=history.models.thumbnailUploadPath)),
                ('footage', models.FileField(upload_to=history.models.footageUploadPath)),
                ('lost', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
